#!/usr/bin/env bash
# Auto-generated by aicommit — do not edit by hand.
# Regenerate after adding/removing version files with: aicommit --remap
#
# Increments THIS project's version across all known files.
# Usage: .aicommit/bump-version.sh <new_version> [old_version]
#   new_version  the version to write (with or without a leading 'v')
#   old_version  optional; if given, only that exact version is replaced
set -euo pipefail

NEW="${1:?usage: bump-version.sh <new_version> [old_version]}"
NEW="${NEW#v}"
OLD="${2:-}"
SEMVER='[0-9]+\.[0-9]+\.[0-9]+'

# Run from the repo root (parent of this .aicommit directory)
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

bump_line() {
    local file="$1" anchor="$2" esc
    if [[ ! -f "$file" ]]; then
        echo "  skip (missing): $file" >&2
        return 0
    fi
    # Escape only ERE metacharacters so the literal anchor is a safe sed address
    esc=$(printf '%s' "$anchor" | sed 's/[][\\^$.*+?(){}|]/\\&/g')
    if [[ -n "$OLD" ]]; then
        sed -i -E "/$esc/ s/${OLD//./\\.}/${NEW}/g" "$file"
    else
        sed -i -E "/$esc/ s/${SEMVER}/${NEW}/g" "$file"
    fi
    echo "  updated: $file" >&2
}

bump_line 'package.json' '"version": "4.3.10"'
